### ISSUE TITLE
Conflicting IDs

### ISSUE THREAD

**Issue by temdur** [belathus/eldritch_revolution#1]
Eldrich Revolution version 1.15.20160811

Got several crashes at start up:
- java.lang.IllegalArgumentException: Duplicate enchantment id! class tb.common.enchantment.EnchantmentTainted and class org.cyclops.evilcraft.enchantment.EnchantmentBreaking Enchantment ID:101
- java.lang.IllegalArgumentException: Duplicate enchantment id! class tb.common.enchantment.EnchantmentVaporising and class org.cyclops.evilcraft.enchantment.EnchantmentLifeStealing Enchantment ID:102
- java.lang.RuntimeException: Biome ID 105 was overridden by the biome Degraded (org.cyclops.evilcraft.world.biome.BiomeDegraded)!

**Comment by belathus** [comment]
This is the issue that keeps rising from the dead.

Do me a favor and check if you have an extra config folder.

**Comment by temdur** [comment]
There was no second config folder.

Copied the content of the /atl/downloads/config20160813.zip into the instances folder. And run out of disk space.

Looks like the installation of the pack need approximate 1.1GB. 212MB for the atl/Downloads; 570MB for the instance; and 330MB for as temporary cache.

The 330MB are only a assumption.

At the first attempt the ATLauncher said "successfully installed" So I had no clue to look at the disk space.
