### ISSUE TITLE
JEI Not Showing

### ISSUE THREAD

**Issue by Daardain** [belathus/eldritch_revolution#15]
![image](https://cloud.githubusercontent.com/assets/22123687/18414099/da7c3164-7772-11e6-836d-eb591e836a8f.png)
This Is The First Issue, Yes I've Tried Pressing "O", I've Rebound The Key To Toggle It On And Off Multiple Times To No Avail... I've Looked It Up But Found Nothing, I Need Help....

**Comment by Divineaspect** [comment]
Eitehr change the shape of your window to be wider, or lower your GUI size, and it should appear.

**Comment by belathus** [comment]
Yeah, this is a problem with having potion effects and a GUI scale of auto. You'll be able to see JEI if you get rid of the potion effect, use a crafting table, or open a chest.

Unfortunately there isn't much we can do about this other than what we already mentioned, so I am closing this issue.
