### ISSUE TITLE
Dependency loop affecting Seventh Seal: Plague

### ISSUE THREAD

**Issue by Whaffles** [belathus/eldritch_revolution#17]
Seventh Seal: Plague currently requires the player to have at least 1 point of "ResealPlague."

Changing the "inverted" value for the "Has Points" condition that checks for the "ResealPlague" point fixes the dependency issue and causes the quest to display what must be the correct description ("You need to have less than 1.0 ResealPlague").

**Comment by Divineaspect** [comment]
Good Catch, fixed for 3.20
