### ISSUE TITLE
Dagon's Blessing can not be completed

### ISSUE THREAD

**Issue by Whaffles** [belathus/eldritch_revolution#19]
One of the requirements to complete Dagon's Blessing is to be currently effected by potion effect 80 ("Positive Potion Effect"). This requirement is impossible to meet, as when effect 80 is applied to a player, it is immediately removed, and replaced with another random potion effect.

Requiring effect 78 ("Revival") instead would fix the issue, and may also be just as thematically effective.

**Comment by Divineaspect** [comment]
fixed in 3.20
