### ISSUE TITLE
Bug that causes crashing.

### ISSUE THREAD

**Issue by donq123** [belathus/eldritch_revolution#2]
It all started when a quest gave me dispel and caused me to crash.
I can't load back into the world now cause I have dispel on me.

**Comment by belathus** [comment]
Any idea which quest?

Assuming the dispel effect is a potion effect, you should be able to edit your player file to remove it using an NBT editor. I think that if you play SSP, that'll be the level.dat file.

**Comment by donq123** [comment]
It is one of the gates quest i thinks, it procs a few times, just have to remove my armour.

**Comment by belathus** [comment]
Gotcha. I will check it out. If it crashes me, too, we'll change that up.

**Comment by Divineaspect** [comment]
This is caused by the potion IDs reassigning due to... something.
Manually fixing.
