### ISSUE TITLE
Eleventh Seal: Time may be incompletable

### ISSUE THREAD

**Issue by Whaffles** [belathus/eldritch_revolution#20]
The quest requires a block to be broken for the conditions of the quest to be met, but there are no blocks listed in the filter for acceptable blocks.

Additionally, this quest, if functioning, would produce a popup notification every time a block is broken, which would obviously be rather obnoxious. Would probably be best to disable the popup, reduce the frequency this quest could be completed, or maybe even both.

**Comment by Divineaspect** [comment]
fixed in 3.20
