### ISSUE TITLE
Intangible Progression not working

### ISSUE THREAD

**Issue by Emmilseafire** [belathus/eldritch_revolution#23]
I've been working through intangible and for some reason soul transfusion didn't appear in the guide. I used the recipe to craft it anyway (thinking it would then show up) and it still never appeared. I was able to use the transfuser and upon using it it came up saying I had learnt it however upon opening the book there was no entry for it at all. It has now continued to not record my progress in the book

**Comment by Divineaspect** [comment]
After dying you may need to either quit your own team, or relog to reinit progression
