### ISSUE TITLE
Crashing on world load, possibly to do with Buildcraft?

### ISSUE THREAD

**Issue by mobar00** [belathus/eldritch_revolution#27]
I've been playing a solo Eledritch Revolution world for a little over a month, with a couple isolated crashes that seem to have fixed themselves with restarts. 
I was on a couple days ago, and one of the things I build was a BC refinery, pumping through some fluid pipes from a dark tank, and into a BC tank. It was fine at the time, but every time I've tried to log on since then, the world crashes while loading. I'm attaching the latest crash report here (hopefully I do it right)
[crash-2017-03-12_20.53.08-server.txt](https://github.com/belathus/eldritch_revolution/files/840046/crash-2017-03-12_20.53.08-server.txt)

I believe the main error is referred to with the statement 

> "Exception while updating neighbours java.lang.NullPointerException: Exception while updating neighbours"

which is followed in the log by  a bunch of lines referencing some generic sounding things like FallingBlockExtensions and Minecraft servers, but the interesting line in the middle is the reason I mentioned the buildcraft tank:

>      at buildcraft.factory.TileTank.func_73660_a(TileTank.java:79)

I've never debugged a world crash issue like this before, so I'm not really sure where to start. Any help is greatly appreciated - I really like this modpack, and I don't want to lose my world like this.

**Comment by Divineaspect** [comment]
before loading up the world try disabling repose (which is the source of falling blocks which uses farseek as a library). You can turn it back on after the world has loaded.

**Comment by mobar00** [comment]
Sweet that seems to have worked. Too bad though, I like Repose.

**Comment by Divineaspect** [comment]
You can turn it back on, it's only a rare issue with falling blocks interacting with the non full block state of a few buildcraft blocks and I think oil sands.
