### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by theilsomers** [belathus/eldritch_revolution#3]
made an account just to inform you of these issues i'm having not sure if someone else is having the issues.
1. The first issue i ran into is that the Path of the Ranger, when you die and recollect your belongings from your corpse, none of the path procs String Bow, On the Hunt and Endless Quiver does not proc until i save and exit and reload to fix it.
2. Using Journey map to teleport to waypoints some times doesn't load that chunk and surrounding chunks leaving you floating on nothingness until a restart as well. ( Doesn't happen every teleport but occasionly it does.)
3. Since the modpack is still new not much info is out on it i am unable to see where my points are such as dominion or tech points so i can figure out what next thing i'm going to unlock for progression. Unless there is a chat command or maybe something within the GUI that i'm not seeing it's hard to tell whats available for me.
4. Some items with in the Progression Book GUI are not showing such as some of the metal bars in the Even More Alloys quest granted you can try to figure it out with JEI but for ease of convience we should be able to see what those items are. There are other quests that don't show what the items are what all of them are right now i don't know.
5. There are several quests that are not registering my kills such as Arachnids it says i've killed 3/33 i've killed alot more then that but they aren't registered do they have to be killed by sword or is any weapon okay or is there a certain condition?
6. i had a mishap and died in the Nether in lava well i didn't want to but i had to go into creative to the bottom of the lava ocean to collect my belongs. Now i'm not sure if there is anything you can do but maybe have the corpse appear on a block above the lava or water or what not to help facilitate getting items back.

As you can tell none of these are game breaking just a few major annoyances with the having to restart the world but still able to progress thus far with no problems. Haven't done much with magic on this modpack yet done more tech then anything but so far i'm really enjoying this modpack thank you for your time and consideration and this modpack.

**Comment by Divineaspect** [comment]
1. Shift click with the progression book, and leave your team to get all those things detecting again. works as well as or better then relogging.
2. That's a limitation with your machine. Increasing memory or processor speed may help resolve, as does playing on a server and thus separating the server and client instances from running on the same machine.
3. A Future update, probably within a week or two, will have a progression book which lists your dominion clearly.
4. good point, I'm considering solutions which can be done without progression updates.
5. Melee is often required for kills to count.
6. Is easily solved if you have repose with a few stacks of dirt, sand, or gravel. Without repose I suggest either gravel and a pump, a full suit of cold iron armor, or a fire resistance talisman.

**Comment by theilsomers** [comment]
1. i'll give it a try if it happens again
2. i've used journey map alot on modpacks and have never had that issue so i don't think its the limitation of my pc, not saying it isn't, but i'm not so sure.
3. is it going to show more then just dominion such as tech, ect.
4. would be nice 
5. then that kind of defeats the purpose for the path of the ranger it should count with bows as well.

**Comment by Divineaspect** [comment]
Just got a fix from Joshie for the  ranged damage issue.
