### ISSUE TITLE
Crash related to Assembly table/laser

### ISSUE THREAD

**Issue by Boy-Blue** [belathus/eldritch_revolution#6]
Crash log:
http://pastebin.com/LB9488XE

In game setup:
http://puu.sh/qRPe9/68329e94a3.png

It seems to be the table not being able to decide where to output.

Moving the table, so that it is only adjacent to the chest not chest and metal press seems to have fixed this.

http://puu.sh/qRPDg/3f20c61937.png

Not sure where else to report this. i.e. Buildcraft or Immersive Engineering

**Comment by Divineaspect** [comment]
I suggest reporting it to both of them. More likely to get a response from IE
